### ISSUE TITLE
iOS - "Continue" button title on link page shows "<#Continue#>" when pressed

### ISSUE THREAD

**Issue by heena-wise** [plaid/quickstart#102]
This is related to iOS but I did not find the issue section there so I am writing details in this forum. I have integrated `Plaid` (version 1.1.28) from [Cocoapods](https://cocoapods.org/pods/Plaid) and facing this issue. I have checked on both iOS 12 and iOS 13 devices. I have verified the code in my app with the sample app and its exactly the same. I am sharing the screenshot of the button title when pressed.

![IMG_4735](https://user-images.githubusercontent.com/51880906/77641204-abae1b80-6f81-11ea-8dfd-2bc0e174a636.PNG)

**Comment by afh** [comment]
Hi @heena-wise, thank you for the report, [LinkKit version 1.1.31](https://github.com/plaid/plaid-link-ios/releases/tag/ios%2F1.1.31) was released earlier today, mind giving that a try?

If the issues persists please file a request with https://dashboard.plaid.com/support.
