### ISSUE TITLE
Node quickstart: "clientApp" is not a valid option for plaid.Client

### ISSUE THREAD

**Issue by Senney** [plaid/quickstart#111]
Hey friends,

Setting up the Plaid client using Typescript 3.8.3, and using `plaid@5.0.0`. I've been following the Quickstart guide for node, and it sets up the plaid client with a `clientApp` setting:
https://github.com/plaid/quickstart/blob/fb50206fea984133c54dfa79fd9b9c36398f6347/node/index.js#L56

When attempting to do the same, Typescript helpfully informs me that `clientApp` is not a a property of the `ClientOptions` type.

![image](https://user-images.githubusercontent.com/375520/82164580-90b7a380-986e-11ea-8f48-acecea56f11f.png)

Is this a valid option, or is it just missing from the types?

Cheers!
Sean

**Comment by daniellacoste** [comment]
Yo @Senney,

This looks like a missing field on our end; I'll escalate this to our engineering team to take a look. Thanks!

**Comment by skylarmb** [comment]
fixed: https://github.com/plaid/plaid-node/pull/302
