### ISSUE TITLE
Quickstart doesn't serve correct html file

### ISSUE THREAD

**Issue by Colman** [plaid/quickstart#143]
When doing the quick start in either python or node, going to localhost:8000 just gives the text "../../html/index.html". Shouldn't it serve the file from that location rather than the path name text?

**Comment by avachali** [comment]
I ended up copying the html and css files from the root dir into resources in the java project to make it work. Should be similar for the other example sets as well. Will create a PR for java.

**Comment by skylarmb** [comment]
Are you on a windows machine? Did you clone the repo with symlinks? Please see this note in the README
 
![image](https://user-images.githubusercontent.com/7543705/93127615-0ef04f00-f683-11ea-8f4b-945dcce391fa.png)

**Comment by parkerrasmussen** [comment]
@skylarmb I am running on a windows machine, and I used the above clone command but it failed to create symlinks in multiple places. See below for the error. Any help would be greatly appreciated. 
![Screenshot 2020-09-27 002628](https://user-images.githubusercontent.com/66753377/94356806-1c7ce000-0058-11eb-9366-0ba2c4ff7b66.png)

**Comment by avachali** [comment]
@parkerrasmussen Try opening your command prompt in Admin mode and run the clone command. That oughta fix the permission issue.

**Comment by parkerrasmussen** [comment]
@avachali Thanks for the quick response. It almost worked perfectly. It now loads up a webpage, but it gives this error. I've input my keys into my .env file so I don't think that's been done incorrectly. I've even attempted a workaround solution to just place the keys directly into the server.py file to see if the .env pull was having issues. It also did not work. 

![image](https://user-images.githubusercontent.com/66753377/94467693-ec812a00-0188-11eb-95f4-edf13da7fb19.png)

**Comment by parkerrasmussen** [comment]
For reference, this is my .env file (i've removed my keys, obviously) 
![image](https://user-images.githubusercontent.com/66753377/94467882-2eaa6b80-0189-11eb-8745-17ffa4e905e9.png)

**Comment by avachali** [comment]
I was using the java example and it seems to be working fine. Just spun up the python instance and it works as well. I did notice that it wasn't picking up values from the .env file, so I hard coded into server.py and it connected without issues.

**Comment by parkerrasmussen** [comment]
Ok I figured it out. The Client ID and Secret must be hard coded into server.py, however, the other data should be brought in using the getenv() functions already in the server.py.

Thanks for all your help @avachali

**Comment by aeidelson** [comment]
@Colman Please let us know if the above fixes don't work and you're still experiencing issues.

Thank you!
