### ISSUE TITLE
OAuth flow does not work on Development environment

### ISSUE THREAD

**Issue by josefblaha** [plaid/quickstart#144]
## Problem
I wanted to use Node.js Quickstart to try to get data from a real bank account. I used Plaid Development environment for that.

The Quickstart fails with bad request, because ``redirect_uri must use HTTPS``. Apparently the redirect URL ``http://localhost:8000/oauth-response.html`` works only in Sandbox environment, and Development and Production require HTTPS.

## Expected behavior
- This limitation should be documented. I found no mention of that.
- The Quickstart could include steps for hosting on HTTPS.

## Workaround
To serve the Quickstart on self-signed HTTPS on localhost:
1. Generate a self-signed certificate, e.g. in Bash:
```
openssl req -nodes -new -x509 -keyout server.key -out server.cert
```
2. Add additional modules to `index.js` and load the generated cert:
```
var fs = require('fs');
var https = require('https');
var key = fs.readFileSync('server.key');
var cert = fs.readFileSync('server.cert');
```
3. Replace the server creation with:
```
var server =
  https.createServer({
    key,
    cert
  }, app)
  .listen(APP_PORT, function() {
  console.log('plaid-quickstart server listening on port ' + APP_PORT);
});
```
4. Change your URLs to HTTPS in:
- ``oauth-response.html`` 
- ``index.html`` (at the begining of ``render_page`` function)
- Env variable
- Plaid account configuration

**Comment by skylarmb** [comment]
hello @josefblaha thanks for this feature request! I will add documentation to the README in the meantime that clarifies this restriction.

**Comment by toniree** [comment]
Just to clarify my confusion, this is what is necessary to support Linking Wells Fargo Accounts in the Development environment if I used the code in this repo to integrate with Plaid, right? 

Also thanks for the comprehensive quickstart guide, it was definitely one of the more helpful examples for 3rd party integrations out there.

**Comment by skylarmb** [comment]
https is required for all institutions if you arent using the Sandbox env. The reason those were working is probably because those institutions are not OAuth enabled (yet!).

**Comment by skylarmb** [comment]
https://github.com/plaid/quickstart/pull/148

**Comment by skylarmb** [comment]
@josefblaha I clarified the documentation. It's unlikely we will add localhost https support to this repo due to the added complexity (this repo is supposed to get you up and running with test data as fast as possible). Thanks for the suggestion! This is always something you can do in your own app as you start to integrate with Plaid.
