### ISSUE TITLE
Quickstart- Java: Html and css files are not in correct location

### ISSUE THREAD

**Issue by avachali** [plaid/quickstart#145]
In the java example, the html and css files refer to location from the root directory. eg: index.html has this in it "../../../../../html/index.html".

**Comment by skylarmb** [comment]
Yes, this file is a symlink to the html file in the root of the repo. Are you on a windows machine? If so, maybe you did not clone the repo using symlinks. Please see this note in the README

![image](https://user-images.githubusercontent.com/7543705/93127523-eec09000-f682-11ea-8524-9211754f0fdb.png)

**Comment by avachali** [comment]
Yup that works! Thanks @skylarmb !
One addl. step I had to do was to run git bash on windows as an admin user to get around permission issues when symlinks were being created.
I'll close out my pull request and this issue :)
