### ISSUE TITLE
country_codes must be a non-empty string array

### ISSUE THREAD

**Issue by nickcanarelli** [plaid/quickstart#155]
I continue to get the following error: 
```
Error Code: INVALID_FIELD
Error Type: INVALID_REQUEST
Error Message: country_codes must be a non-empty string array
```

**.env**
```
APP_PORT=8000
PLAID_CLIENT_ID='xxx'
PLAID_SECRET='xxx'
PLAID_PRODUCTS='transactions'
PLAID_COUNTRY_CODES='US'
PLAID_ENV='sandbox'
```

Does anyone else have this issue, if so were you able to fix it?

Edit: Had to wrap all `country_codes: PLAID_COUNTRY_CODES` with `[]` to look like `country_codes: [PLAID_COUNTRY_CODES]`

**Comment by Mendoza920** [comment]
I need help

**Comment by phoenixy1** [comment]
@nickcanarelli I believe that @skylarmb 's changes to the .env file at the end of October resolved this issue; please feel free to re-open if it still occurs.
