### ISSUE TITLE
Go: CreatePublicToken not in plaid-go package

### ISSUE THREAD

**Issue by jdumont0201** [plaid/quickstart#156]
Hi folks, 

The quickstart/go/server.go file on line 281 calls   CreatePublicToken on the client
```	publicToken, err := client.CreatePublicToken(accessToken) ```

but the function is missing in the plaid-go package.

https://github.com/plaid/plaid-go/search?q=CreatePublicToken      
is empty.

**Comment by skylarmb** [comment]
hi @jdumont0201 that function was removed in https://github.com/plaid/plaid-go/pull/145 and released in v6.0.0. This quickstart app still uses an older version of `plaid-go`. It's on our list to upgrade to the latest version, but thanks for flagging.
