### ISSUE TITLE
Python quickstart doesn't run on Python3 out of the box.

### ISSUE THREAD

**Issue by justanr** [plaid/quickstart#16]
Decided to pick up plaid to play with it, and when installing on Python3 it fails due to wsgiref (there is a print statement in its setup.py), and after deleting that dependency, server.py also contains print statements.

The fix seems relatively straightforward of changing the calls in server.py to print function calls and conditionally installing wsgiref depending on if the target Python install is 2 or 3.

Happy to submit a PR to address this.

**Comment by pbernasconi** [comment]
Hey @justanr - thanks for raising the issue regarding support for Python 3. We definitely want to support all versions of Python that developers might want to use with our quickstart, including Python 3.

If you feel you might have a fix to this issue, we'd gladly accept any PR to address this!

**Comment by michaelckelly** [comment]
@justanr - @jncraton fixed this via https://github.com/plaid/quickstart/pull/20, please re-open this issue fi you are still having trouble running the quickstart! You'll want to ensure you pull down the new changes first.
