### ISSUE TITLE
Sudden 'Internal Error Ocurred' Upon submitting Username and Password (/link/item/create call)

### ISSUE THREAD

**Issue by toniree** [plaid/quickstart#168]
Hi, this integration has been working fine until sometime last week/today. When using the Sandbox server, the 'user_good' 'pass_good' combination used to work fine, but now I'm receiving a page stating "Internal error Occured, we have been notified about the problem". The error message I am seeing in the console is: "the service responded with a status of 429 development.plaid.com/link/item/create".

This has been working fine on one of our app servers which we haven't changed code for in a while, so guessing it's a change on Plaid's side. Here's a reproducible example, where "index2.ejs" is similar to the given index.html:

```
# In app.py:
//Endpoint to reach Plaid Banking welcome screen
@app.route('/plaid/development/<string:customerId>')
def indexDevelopment(customerId):
  return render_template(
    'index2.ejs',
    plaid_public_key=PLAID_PUBLIC_KEY,
    plaid_environment="development",
    plaid_products=PLAID_PRODUCTS,
    plaid_country_codes=PLAID_COUNTRY_CODES,
    plaid_oauth_redirect_uri="http://localhost:5000/oauth-response2.html",
    plaid_oauth_nonce=PLAID_OAUTH_NONCE,
    customerId=customerId
  )

```

**Comment by toniree** [comment]
Upon taking a deeper dive, seems like you were down for a bit on the 16th, and I'm seeing that the /link/item/create call is triggering a rate limiter. Guessing the rate limiter was a first line of defense and it's causing false positives in my implementation? (Although it looks like the call is only made once per session)

**Comment by phoenixy1** [comment]
@toniree Yep -- the symptoms you're describing seem consistent with a known outage in late November that was resulting in spurious rate-limit errors in some cases.  The issue should now be resolved.
