### ISSUE TITLE
Getting invalid key message

### ISSUE THREAD

**Issue by chuymax** [plaid/quickstart#17]
- Sign up for a free plaid developer account.
- git clone quickstart
- change client_id, secret, public_key and environment=development (python=>server.py, node=>set environment variables as explained on the instructions.
- Start either python or node application as indicated on the instructions.
- Attempt to connect to a bank
- I get the following message: Invalid key. The public key you provided was incorrect. Your public key is available from the Plaid dashboard.
- I get the following message on stdout when running the python application:
```
  Development is not intended for production usage.
                Swap out url for https://api.plaid.com
                via Client.config before switching to production
```

**Comment by hkhan09** [comment]
I had to override the string: 'key: '{{ plaid_public_key }}',' in the python/templates/index.ejs file to my public key in order to get the python walkthrough to work.
