### ISSUE TITLE
Custom User Configuration JSON

### ISSUE THREAD

**Issue by debdutgoswami** [plaid/quickstart#170]
In the Plaid Docs, we have a custom user configuration 

```
{
  "override_accounts": [
    {
      "type": "depository",
      "subtype": "checking",
      "transactions": [
        {
          "date_transacted": "2019-10-01",
          "date_posted": "2019-10-03",
          "currency": "USD",
          "amount": 100,
          "description": "1 year Netflix subscription"
        },
        {
          "date_transacted": "2019-10-01",
          "date_posted": "2019-10-02",
          "currency": "USD",
          "amount": 100,
          "description": "1 year mobile subscription"
        }
      ]
    }
  ]
}
```

Can you provide an exhaustive JSON while can support all the products?

My Products config `PLAID_PRODUCTS=transactions,auth,identity,assets,liabilities,investments`.

Error:

![Screenshot from 2020-12-16 13-08-01](https://user-images.githubusercontent.com/40338044/102324268-9cf01480-3fa7-11eb-8788-4a9634a2c08e.png)

The error does not show up if we just keep `PLAID_PRODUCTS` as `transactions,auth,identity`

**Comment by phoenixy1** [comment]
@debdutgoswami can you explain a little bit more about your use case?  It's a bit unusual for a single customer to use every Plaid product, and if you just want to have a Sandbox account that has pre-populated data that we picked, the default Sandbox account (user_good/pass_good) should provide that, so to help with your problem it would be useful to understand the scenario you want to support.  Thanks!

**Comment by debdutgoswami** [comment]
@phoenixy1 For now, we are just testing it. So, need a sandbox account which provided all the data. When in sandbox, upon using `user_good`, it is still showing the same error.

**Comment by skylarmb** [comment]
hey there @debdutgoswami just doing some houskeeping on old issues... If you need to test `investments` and `liabilities` data in sandbox, try initializing the item without the `auth` product, and vice versa. If you are testing `auth`, do not initialize with `investments` or `liabilities` products. Once the item is initialized feel free to make calls for any products you want, you dont need to have them initialized in Link for them to be accessible. This may solve your issue in the sandbox environment as its just a quirk of our sandbox environment at the moment (I've made an internal ticket to track this).

In production, as @phoenixy1 mentioned, it's a good idea to **not** add all the products in the products array as it has many implications. See more here: https://plaid.com/docs/link/best-practices/#choosing-when-to-initialize-products
