### ISSUE TITLE
Set Access Token called with wrong parameter

### ISSUE THREAD

**Issue by WardBenjamin** [plaid/quickstart#172]
In one of the calls to /api/set_access_token from the Link Account page, an `access_token` parameter is sent instead of the expected `public_token`.

https://github.com/plaid/quickstart/blob/9ccc96567eaec7a77209676a1693387cc93a32d0/html/index.html#L483

**Comment by skylarmb** [comment]
hey there, this is outdated now. We have completely re-written this app using react for the frontend. Go check it out and let us know what you think!
