### ISSUE TITLE
npm ERR! command sh -c react-scripts start

### ISSUE THREAD

**Issue by elcodeco** [plaid/quickstart#177]
Hi, 

I am running the quickstart on a Apple M1 without Docker. Following the instructions, this is what I received upon starting the frontend application. Any ideas? 

#
# Fatal error in , line 0
# Check failed: allocator->SetPermissions(reinterpret_cast<void*>(region.begin()), region.size(), PageAllocator::kNoAccess).
#
#
#
#FailureMessage Object: 0x16fd98ab8
 1: 0x100167d34 node::NodePlatform::GetStackTracePrinter()::$_3::__invoke() [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
 2: 0x100eb42fc V8_Fatal(char const*, ...) [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
 3: 0x100805928 v8::internal::wasm::WasmCodeManager::Decommit(v8::base::AddressRegion) [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
 4: 0x100808fa8 v8::internal::wasm::NativeModule::FreeCode(v8::internal::Vector<v8::internal::wasm::WasmCode* const>) [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
 5: 0x100818190 v8::internal::wasm::WasmEngine::FreeDeadCodeLocked(std::__1::unordered_map<v8::internal::wasm::NativeModule*, std::__1::vector<v8::internal::wasm::WasmCode*, std::__1::allocator<v8::internal::wasm::WasmCode*> >, std::__1::hash<v8::internal::wasm::NativeModule*>, std::__1::equal_to<v8::internal::wasm::NativeModule*>, std::__1::allocator<std::__1::pair<v8::internal::wasm::NativeModule* const, std::__1::vector<v8::internal::wasm::WasmCode*, std::__1::allocator<v8::internal::wasm::WasmCode*> > > > > const&) [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
 6: 0x100815e98 v8::internal::wasm::WasmEngine::PotentiallyFinishCurrentGC() [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
 7: 0x10081730c v8::internal::wasm::WasmEngine::ReportLiveCodeForGC(v8::internal::Isolate*, v8::internal::Vector<v8::internal::wasm::WasmCode*>) [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
 8: 0x1008176bc v8::internal::wasm::WasmEngine::ReportLiveCodeFromStackForGC(v8::internal::Isolate*) [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
 9: 0x1003a0e04 v8::internal::StackGuard::HandleInterrupts() [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
10: 0x1006dc5c0 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
11: 0x1009cd90c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
12: 0x1009666b0 Builtins_InterpreterEntryTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
13: 0x100966614 Builtins_InterpreterEntryTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
14: 0x100966614 Builtins_InterpreterEntryTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
15: 0x100966614 Builtins_InterpreterEntryTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
16: 0x100966614 Builtins_InterpreterEntryTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
17: 0x100966614 Builtins_InterpreterEntryTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
18: 0x100966614 Builtins_InterpreterEntryTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
19: 0x100966614 Builtins_InterpreterEntryTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
20: 0x10095dc44 Builtins_ArgumentsAdaptorTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
21: 0x100966614 Builtins_InterpreterEntryTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
22: 0x10095dc44 Builtins_ArgumentsAdaptorTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
23: 0x100966614 Builtins_InterpreterEntryTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
24: 0x100966614 Builtins_InterpreterEntryTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
25: 0x100966614 Builtins_InterpreterEntryTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
26: 0x100966614 Builtins_InterpreterEntryTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
27: 0x100966614 Builtins_InterpreterEntryTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
28: 0x10095dc44 Builtins_ArgumentsAdaptorTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
29: 0x100966614 Builtins_InterpreterEntryTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
30: 0x10095dc44 Builtins_ArgumentsAdaptorTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
31: 0x100966614 Builtins_InterpreterEntryTrampoline [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
32: 0x100a19b9c Builtins_PromiseFulfillReactionJob [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
33: 0x100985788 Builtins_RunMicrotasks [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
34: 0x100963da8 Builtins_JSRunMicrotasksEntry [/Users/jason/.nvm/versions/node/v15.8.0/bin/node]
35: 0x160008000
npm ERR! code 1
npm ERR! path /Users/jason/code/quickstart/frontend
npm ERR! command failed
npm ERR! command sh -c react-scripts start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jason/.npm/_logs/2021-02-17T20_26_54_399Z-debug.log

**Comment by phoenixy1** [comment]
@elcodeco Sorry for the trouble!  I found https://github.com/netlify/cli/issues/1800 which suggests that this might be due to a bug in the version of Node.js or npm you are using -- can you try upgrading Node.js / npm to the latest and seeing if that fixes the problem?

**Comment by skylarmb** [comment]
hey @elcodeco feel free to reopen this if necessary, but I am closing this issue for now as it does not appear there is any action item for us here.
