### ISSUE TITLE
Invalid Host Headers

### ISSUE THREAD

**Issue by apeg3200** [plaid/quickstart#184]
Company : Mariner Finance
Department: Online Lending
Developer : Alex Peguero
Email : apcruz@marinerfinance.com

So, we installed the container (quick_start) in our development cloud environment. We are having issues connecting with the application. The error it keeps throwing is "Invalid Host Headers". This container was given it's own docker-subtnet. We have other containers running in their own subnet environment. I think the issue has to do with "react" and it using the "proxy" service. I know that from past experience using react somethings the browser might through "Cross-Origin" issues when trying to make request outbound the "FQDN". Especially in development. A good way around that is a "proxy server". I believe this might be the culprit. Since we're using a WAF to establish "Content Security Policies" for all web applications. When we remove "'proxy': 'http//localhost:8000'" from the package.son file the page renders but it then throws another error. I've attached images and text file to this support ticket. I think if you can remove the "proxy" dependency all together the UI will work. The backend server resolves find. I added test route ( requestMethod: "GET") that return an "OK" status ( { success: "OK", status: 200 }).

Please let us know if you need anything else from us.

Thanks,

Alex

**Comment by skylarmb** [comment]
Hi there @apeg3200! The quickstart app is meant as a `localhost` demo of the Plaid API and Plaid Link module, but not as an app we recommend deploying in any sort of production environment. Docker is provided as a faster way of getting it up and running locally without worrying about language versions and dependencies. 

If you intend to use this as a starting point to develop your app, I would **highly** recommend addressing certain [assumptions](https://github.com/plaid/quickstart/blob/master/node/index.js#L41-L45) the code makes for the sake of simplicity with the intent of this being a _local_ playground for learning about Plaid and not being deployed in a publicly accessible place. Happy to let you know what some of these things are are if that is what you intend to do with this app. As you have discovered, the localhost proxy config is one of these assumptions we make.

All that said, the react docs have specific instructions on how to solve your issue for hosting the react app with a proxy on a FQDN. You should be able to create the file `frontend/.env.development` or `frontend/.env` and add some environment variables there that will make the proxy config work: https://create-react-app.dev/docs/proxying-api-requests-in-development/#invalid-host-header-errors-after-configuring-proxy 

I am not sure if you would need to mess with `frontend/src/setupProxy.js` but that file is available as well if you need to make changes to the proxy behavior.

**Comment by skylarmb** [comment]
hi @apeg3200 I am going to close this issue as there is no action or change to this codebase required on our end. Feel free to continue commenting here and I will follow up even though the issue is closed, just closing for housekeeping purposes!
