### ISSUE TITLE
Support for Update Mode

### ISSUE THREAD

**Issue by akerl** [plaid/quickstart#191]
I’m trying to sort out how to use Update Mode (https://plaid.com/docs/link/update-mode/) for a token that’s expired. Some of the backends have comments about generating tokens to use for Link Mode, but I can’t for the life of me figure out how to actually proceed w/ the resulting token.

How am I meant to actually proceed through Update Mode?

**Comment by phoenixy1** [comment]
(Apologies for the very late response, hopefully you already got this answered, but better late than lever...)

Are you trying to use update mode to renew a token with an expiration time, like a link token?  Update mode is used to renew access_tokens that no longer work, it can't be used to renew an expired token.

**Comment by phoenixy1** [comment]
Closing this issue due to age / no response, please re-open if you still need help
