### ISSUE TITLE
Failed to compile - Typescript error TS2307

### ISSUE THREAD

**Issue by WebWallen** [plaid/quickstart#199]
I made it to the end of your Quick Start guide and ran into a problem not discussed in docs or any Github issues I could find. 

The webpage opens for a split second on localhost:3000, but then shows this error message.

Any advice or insights RE: what might be causing this (and how to fix it)? 

Thanks in advance!

![plaid-error](https://user-images.githubusercontent.com/52639754/112180176-b1a8fd80-8bd1-11eb-8725-22ef5c6d797a.png)

**Comment by cgfarmer4** [comment]
hey @WebWallen- can you check your `node_modules` folder where `npm` installs the depencencies and see if `plaid` is listed in there? If so, plus out the directory and ensure that file is listed.

**Comment by WebWallen** [comment]
NPM installed many dependencies, but left out that one. Is there any way to get the relevant code? I searched for the specific file on Google and Github, but am not seeing a relevant result.
![plaid-error-2](https://user-images.githubusercontent.com/52639754/112230147-c3f35d80-8c0a-11eb-9af2-012c4d23616f.png)

**Comment by stephenjayakar** [comment]
hey @WebWallen!

looks like `npm` might have installed the wrong version or didn't do it at all. pretty odd. are you running the `make up` command from the root of the quickstart repo? 

also ideally delete `quickstart/node/node_modules` if issues persist, and try `make up` again.

**Comment by WebWallen** [comment]
The issue persisted and I'm not sure why, so I used the nuclear option (deleted the repo and started from scratch). The Quickstart link opened correctly on the second attempt. Strange. But if it works, it works!
