### ISSUE TITLE
 the list of institutions is not shown

### ISSUE THREAD

**Issue by danieljonguitud** [plaid/quickstart#21]
I'm trying to use the Plaid Example Walkthrough but looks like the Link button is not working on python 3. Could be a compatibility problem?

**Comment by nathan-hall** [comment]
I'm encountering the same thing. It doesn't matter if I use Ruby or Python walkthroughs.

**Comment by michaelckelly** [comment]
@nathan-hall - How are you running the Quickstart app? We haven't heard reports of issues from other developers in recent days.

**Comment by nathan-hall** [comment]
I'm running from terminal following the steps of doing the git pull, running the  requirements.txt setting the environ variables for the keys etc... then running the server.py. I also am using Python 3 if that is an issue for compatibility.

**Comment by nathan-hall** [comment]
@michaelckelly When inspecting the empty list of institutions here's the errors that its showing.

![image](https://user-images.githubusercontent.com/4693005/36557522-7b3f4208-17d6-11e8-9f16-f313cf136b16.png)

**Comment by michaelckelly** [comment]
@nathan-hall - Please double check the `public_key` you are using to start the quickstart. That is the root issue you're encountering. You'll want to start the Python quickstart as:

```
PLAID_CLIENT_ID=clientID PLAID_SECRET=secret PLAID_PUBLIC_KEY=publicKey python server.py
```

Your API keys are available from the [Dashboard][1]

[1]: https://dashboard.plaid.com/account/keys

**Comment by nathan-hall** [comment]
@michaelckelly Thanks! That did the trick. I am still getting an error about credentials from the wells fargo login... but I can at least see all the institutions listed now.

**Comment by michaelckelly** [comment]
@nathan-hall - If you are using our [Sandbox environment](https://plaid.com/docs/api#sandbox), be sure to use our Sandbox credentials:

```
username: user_good
password: pass_good
```
