### ISSUE TITLE
Invalid value "undefined" for header "PLAID-CLIENT-ID"

### ISSUE THREAD

**Issue by TheDutchMC** [plaid/quickstart#217]
Hey there,

I'm unable to get this quickstart going due to the error `Invalid value "undefined" for header "PLAID-CLIENT-ID"` which is thrown on the backend when I load the frontend.

Here's my .env with some redacted values:
```env
PLAID_CLIENT_ID=REDACTED
PLAID_SECRET=REDACTED
PLAID_ENV=development
PLAID_PRODUCTS=auth,transactions
PLAID_COUNTRY_CODES=NL
PLAID_REDIRECT_URI=REDACTED
```

I've added a `.env` in `frontend/` as per #184:
```env
DANGEROUSLY_DISABLE_HOST_CHECK=true
```

I'm using the Docker container method, however I am running it on Kubernetes. I'm routing `/` to the frontend, and `/api` to the backend, since that is what it seems to be making requests to.

See the screenshot for the error in the frontend:
![image](https://user-images.githubusercontent.com/28569170/118357787-194d4a80-b57c-11eb-8f6d-796e409a0190.png)

Screenshot of the error in the backend:
![image](https://user-images.githubusercontent.com/28569170/118357802-29fdc080-b57c-11eb-9f50-bd75ce2b34fb.png)

**Comment by phoenixy1** [comment]
Hi @TheDutchMC!  We tried this ourselves but haven't been able to reproduce this issue on a non-Kubernetes setup.  As @skylarmb mentioned in #184, the Quickstart app makes assumptions that you're running it locally and hasn't been configured to support hosting it in this way. Can you reproduce the issue if you are running it locally?

**Comment by TheDutchMC** [comment]
Fair point. Ill see if I can get it working locally. Thinking about it, I dont think I need to keep this app running indefinitely anyways, so that should be fine (Using it as per Firefly-iii's Plaid integration guide)

**Comment by phoenixy1** [comment]
@TheDutchMC Any updates? If it's still not working when configured locally, please let us know, otherwise I plan to close this issue out.

**Comment by TheDutchMC** [comment]
My apologies for the delay, I've been a bit busy of the past week.

I've set up the quickstart as per the guide in the README locally. Connecting to localhost:3000, the frontend shows, gives a 500 for favicon.ico, and the /api/info request is just stuck at pending (No errors that I can see in the backend).

Might be important to note that I had to change the provided docker-compose file, in the file the `name` property was defined under `networks`, which it didn't like. Could that be related?

I've tried the Node and Java backends, both give the same result.

**Comment by phoenixy1** [comment]
@lindawoo-plaid would you be able to take a look at this when you get a chance? I am a bit swamped.

**Comment by lindawoo-plaid** [comment]
@TheDutchMC Why did you have to change the name property in the docker-compose file? Yes, this could have something to do with your error.  What change did you make to it? (I'm trying to reproduce your error)

**Comment by TheDutchMC** [comment]
Hey there,

I had to remove the name property entirely. Docker compose errored with that it was not allowed there

**Comment by lindawoo-plaid** [comment]
@skylarmb, Do you have any idea why Docker would not allow the "networks" property on their docker-compose file?  This property is necessary for it to run on my machine.

**Comment by skylarmb** [comment]
@TheDutchMC what version of docker are you running?

**Comment by TheDutchMC** [comment]
I'm on Docker version `Docker version 20.10.6, build 370c289` and Docker-compose version `docker-compose version 1.27.4, build 40524192`

**Comment by skylarmb** [comment]
hmm @TheDutchMC i am using almost identical versions and I cannot reproduce this network issue, even if i remove the `name` property of the network. 

However, the original error you posted is quite confounding to me. Somewhere your client id from your env vars is not being set correctly and is ending up as `undefined` somewhere deep in the stack (you can see the stack trace points to some sort of internal validation inside Axios) when making a network call to the Plaid API.

If you discard your changes and try a different backend such as python or ruby, what error do you get then? Just the 502 error about the frontend not being able to talk to the API? Or is there an error in the api logs as well?

In the meantime ill continue to play with this to see if i can reproduce something

**Comment by skylarmb** [comment]
Could you confirm that you did not mess with any other env vars that affect networking such as `APP_PORT` or `REACT_APP_API_HOST` or any of the proxy setup e.g. `frontend/src/setupProxy.js` etc.

**Comment by TheDutchMC** [comment]
Honestly, I'm not sure what was going wrong.

I've recloned the repo, faced with the same docker compose error, so I took the key out, and now everyone on the Plaid side works fine.

Not sure what was wrong, but I think it was a one off. I suppose it is then clear to close this issue

**Comment by skylarmb** [comment]
thanks! Ill make a PR to remove `name` from the docker-compose.yml file as it works without it and seems to cause issues for you

**Comment by TheDutchMC** [comment]
Yep guessing as much :D

**Comment by antone29** [comment]
I was getting this same error. I found I was calling for my environment variables in two different places so when i commented one of them out, it worked.
