### ISSUE TITLE
frontend npm install fails

### ISSUE THREAD

**Issue by micottis** [plaid/quickstart#228]
When I run `npm install`, I get:
```shell
up to date, audited 1839 packages in 3s

62 packages are looking for funding
  run `npm fund` for details

49 vulnerabilities (25 low, 9 moderate, 15 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```
I ran `npm audit fix` and `npm audit fix --force` a few times but 11 or 15 high vulnerabilities remain. I deleted the `quickstart` repo and cloned it again but got the exact same issue. Is this normal?

**Comment by phoenixy1** [comment]
@micottis Thanks for the report! yes, this is normal behavior. The npm message is an informative message, it does not mean that the npm installation failed. As the Quickstart app should not be used for production code these issues should not be a problem. This article has some useful context: https://www.voitanos.io/blog/don-t-be-alarmed-by-vulnerabilities-after-running-npm-install/

That said, we will take a look at this issue and see if we can at least reduce the number of vulnerabilities by eliminating or upgrading packages.

**Comment by micottis** [comment]
Great, many thanks @phoenixy1.

**Comment by phoenixy1** [comment]
We eliminated and/or upgraded dependencies on our end and have brought the number of vulnerabilities down to a total of 9.
