### ISSUE TITLE
Python example not working

### ISSUE THREAD

**Issue by varunyn** [plaid/quickstart#235]
Throwing error for `plaid_python==8.0.0b12`
```
ERROR: Could not find a version that satisfies the requirement plaid_python==8.0.0b12 (from -r requirements.txt (line 2)) (from versions: 0.2.0, 0.2.1, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.3.0, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.5.0, 3.0.0, 3.1.0, 3.1.1, 3.2.0, 3.3.0, 3.4.0, 3.5.0, 3.6.0, 3.7.0, 3.8.0, 3.9.0, 4.0.0, 4.1.0, 5.0.0, 6.0.0, 6.1.0, 7.0.0, 7.1.0, 7.2.0, 7.2.1, 7.3.0, 7.4.0, 8.0.0b1, 8.0.0b2, 8.0.0b3, 8.0.0b4)
ERROR: No matching distribution found for plaid_python==8.0.0b12 (from -r requirements.txt (line 2))
```

**Comment by cgfarmer4** [comment]
@varunyn can you share more about your system? it seems like your python dependencies are not finding all the versions as we have released 8 versions post `8.0.0.b4`. https://pypi.org/project/plaid-python/#history

**Comment by varunyn** [comment]
My virtualenv was not set up correctly, was using python 2. It is resolved now. Thanks for the quick response. I am getting this error though when running the app.

Python 3.9.6
macOS: 11.2.3 (Big Sur)


```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sandbox.plaid.com', port=443): Max retries exceeded with url: /link/token/create (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
```

**Comment by cgfarmer4** [comment]
can you try `python 3.7`? `3.9` should work but lets rule that out if possible.

**Comment by varunyn** [comment]
I tried with docker, it is using [python:alpine](https://hub.docker.com/layers/python/library/python/alpine/images/sha256-87389348ff0893831bfa6b2b7340fffcf4d836115f3628166bc63b666ba962c0?context=explore),  python 3.9.5. That works fine

**Comment by phoenixy1** [comment]
@lindawoo-plaid I tried to reproduce this and I could not get the python quickstart to work following the non-docker instructions, I got the error 

```
~/quickstart/python$ python3 server.py
Traceback (most recent call last):
  File "/Users/ahoffer/quickstart/python/server.py", line 2, in <module>
    from plaid.model.payment_amount import PaymentAmount
ModuleNotFoundError: No module named 'plaid'
```

Would you be willing to take a look?

**Comment by lindawoo-plaid** [comment]
@phoenixy1 , "Payment" was changed to "PaymentAmount" in the client libraries.  I think you are using an old version of quickstart?  Have you downloaded recently?

**Comment by phoenixy1** [comment]
This was resolved by updating the instructions around python2. My pip was configured to work with python2
