### ISSUE TITLE
.env file is not loaded before attempting to access variables

### ISSUE THREAD

**Issue by HunterHeston** [plaid/quickstart#246]
Neither plaid PLAID_CLIENT_ID or PLAID_SECRET will ever be set in the current implementation. The error message indicates that the user needs to fill out `.env.example` and move it to `.env`. But the codebase does not load the variables in the `.env` file into the environment before using them. So the user will end up frustrated. 

https://github.com/plaid/quickstart/blob/684f8e5c109d26ef4d260be2a056c54a23174bcc/go/server.go#L39-L44

**Comment by lindawoo-plaid** [comment]
@HunterHeston, This issue has been fixed.  You can reclone if you like.

**Comment by HunterHeston** [comment]
Awesome thanks for the quick fix on this! Going to close the issue.
