### ISSUE TITLE
Error 411 

### ISSUE THREAD

**Issue by farmanp** [plaid/quickstart#25]
I tried logging in my credentials to TJX Rewards and the error was:

INSTITUTION_NOT_RESPONDING | 400 | The financial institution is failing to respond to some of our requests. Your user may be successful if they retry another time.
-- | -- | --

However, I saw a 411 when viewing the response: 

Content-Length: 411

**Comment by michaelckelly** [comment]
@farmanp -- the 411 you saw referred to the response body length, not the HTTP status code that Plaid returned!
