### ISSUE TITLE
.Net version aligned with Stripe?

### ISSUE THREAD

**Issue by dochoss** [plaid/quickstart#258]
Hi Plaid Team,

I'm looking to leverage Plaid to integrate a client with Stripe, but our team is mostly .Net devs.  Pulling down the Java library and rewriting it for .Net would work, but we don't have the bandwidth for that right now.  Any chance of a .Net Plaid library coming any time soon?  You guys provide all the language support that Stripe does, except .Net.  If you could get one started with some basics, I'd be happy to contribute, as would my team!

Thanks for everything you guys are doing.  Keep up the great work!

**Comment by phoenixy1** [comment]
@dochoss Thanks for the kind words! we don't have an official .NET library, but there are a couple community ones we recommend:

https://github.com/viceroypenguin/Going.Plaid
https://github.com/Ackara/Plaid.NET/

**Comment by dochoss** [comment]
Thanks for the recommendations. I'll check them out!
