### ISSUE TITLE
Help - Link / onSuccess / I need the institution name

### ISSUE THREAD

**Issue by johndpope** [plaid/quickstart#264]
this code here (I believe) passes in the public_token - 
https://github.com/plaid/quickstart/blob/master/frontend/src/Components/Link/index.tsx

```javascript
  const onSuccess = React.useCallback(
    (public_token: string) => {
      // send public_token to server
      const setToken = async () => {
        const response = await fetch("/api/set_access_token", {
          method: "POST",
          headers: {
            "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
          },
          body: `public_token=${public_token}`,
        });
        if (!response.ok) {
          dispatch({
            type: "SET_STATE",
            state: {
              itemId: `no item_id retrieved`,
              accessToken: `no access_token retrieved`,
              isItemAccess: false,
            },
          });
          return;
        }
        const data = await response.json();



        dispatch({
          type: "SET_STATE",
          state: {
            itemId: data.item_id,
            accessToken: data.access_token,
            isItemAccess: true,
          },
        });
      };
      setToken();
      dispatch({ type: "SET_STATE", state: { linkSuccess: true } });
      window.history.pushState("", "", "/");
    },
    [dispatch]
  );
```

the code above uses React.useCallback + typescript is a bit foreign to me - and looking for some spoon feeding here to simply get the institution name back like this javascript code. 

```javascript

app.post(`/access_token`, function(req, res) {
    var public_token = req.body.public_token;
    var metadata = req.body.metadata; // I WANT THIS HERE... and I want to save it as below.
    client.exchangePublicToken(public_token, function(error, tokenResponse) {
    if (error != null) {
      console.log('Could not exchange public_token!' + '\n' + error);
      return res.json({error: msg});
    }
    var access_token = tokenResponse.access_token;
    var item_id = tokenResponse.item_id;

    dynamo.addInstitution(item_id, access_token, metadata.institution.name).then(result => {
      res.json({'success': 'true', 'institution': metadata.institution.name});
    });
    });
});
```

This ticket seems related - https://github.com/plaid/quickstart/issues/36
(Though I can't control this on dashboard )

UPDATE
I think I need to fetch this server side...

	pAccountRes, _, err := client.PlaidApi.AccountsGet(ctx).AccountsGetRequest(
		*plaid.NewAccountsGetRequest(iTok.AccessToken),
	).Execute()

**Comment by lindawoo-plaid** [comment]
the onSuccess callback function returns metadata, which includes information on the institution (see our [docs](https://plaid.com/docs/link/web/#link-web-onsuccess-metadata) for a description of this metadata object).  Add that to the parameters in the function. (you will need to import PlaidLinkOnSuccessMetadata from 'react-plaid-link')

const onSuccess = React.useCallback(
    (public_token: string, **metadata: PlaidLinkOnSuccessMetadata**) => { 

**console.log(metadata.institution.name)**

      // send public_token to server
      const setToken = async () => {
        const response = await fetch("/api/set_access_token", {
          method: "POST",
          headers: {
            "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
          },
          body: `public_token=${public_token}`,
        });
        if (!response.ok) {
          dispatch({
            type: "SET_STATE",
            state: {
              itemId: `no item_id retrieved`,
              accessToken: `no access_token retrieved`,
              isItemAccess: false,
            },
          });
          return;
        }

**Comment by johndpope** [comment]
Cool thanks / belongs in the QuickStart sample.

**Comment by johndpope** [comment]
LllkkkooqqMMmqoooeoeksww kemekkrfdddq I will uuszaw

**Comment by johndpope** [comment]
Hi Linda,
I looked through the meta data endpoints - and I can see that it correctly discloses the bank and account names - I don't know who is the person - company tied to the institution. Is that available in a different end point? Eg. I sign in with Chase - Saving Account - but I need to know who I am logged in - eg. John Pope.... 
Where can I get that data?

**Comment by lindawoo-plaid** [comment]
Also, if you're looking for more robust integrations, check out our Plaid
Pattern Sample Apps:
https://github.com/plaid/pattern-account-funding. (this one uses the
identity/get endpoint)
https://github.com/plaid/pattern
