### ISSUE TITLE
Plaid Sandbox - Unable to fetch link_token

### ISSUE THREAD

**Issue by AnnTeh** [plaid/quickstart#286]
Hi Plaid,
I have used PyCharm for the Plaid Sandbox. Followed step by step. I have copied the details from the env example to .env, included the client ID and secret. 

But I have the following issue on the webserver after I have run both the ./start.sh and npm start:

Plaid Quickstart 
A sample end-to-end integration with Plaid 
The Plaid flow begins when your user wants to connect their bank account to your app. Simulate this by clicking the button below to launch Link - the client-side component that your users will interact with in order to link their accounts to Plaid and allow you to access their accounts via the Plaid API.

Unable to fetch link_token: please make sure your backend server is running and that your .env file has been configured correctly. 

Error Code: 
Error Type: 
Error Message:

Do you know is the reason and do I need to do anything with the env file other than copy, paste and fill in relevant information?

Thank you. Please kindly assist.

**Comment by tyliec** [comment]
I'm seeing the same issue, did you resolve this?

**Comment by nfrancque** [comment]
@tyliec I had this problem and it was because I hadn't added `http://localhost:3000` to https://dashboard.plaid.com/team/api.  It's in the docs but easy to miss.

**Comment by tyliec** [comment]
<img width="681" alt="Screen Shot 2022-01-02 at 4 18 27 PM" src="https://user-images.githubusercontent.com/15609358/147893067-d76eeb23-cb4c-4c48-a275-f7aa1200bd5a.png">

@nfrancque Having the same issue - is there some configuration I need to flush?

**Comment by nfrancque** [comment]
I think I had to do something like `make stop; docker image rm quickstart_[whatever you have]; make up`. 

It'd be nice if there was a `make clean` target to delete the docker images.

**Comment by zevaverbach** [comment]
I had a trailing slash in `.env` but not in the API dashboard! Appending that in the dashboard fixed it. D'oh!
