### ISSUE TITLE
About  Expected credential fields but got none

### ISSUE THREAD

**Issue by ZnNozomi** [plaid/quickstart#296]
use ‘https://cdn.plaid.com/link/v2/stable/link-initialize.js’ load the plaid
Step to reproduce:
Launch plaid link
Select Bank
Google Behavior verification 
When you click the back button during the behavior validation step, an error is reported like ‘Expected credential fields but got none’
I can't find a solution on the official website

**Comment by phoenixy1** [comment]
@ZnNozomi thank you for reporting that issue! 

Would it be possible for you to attach a video of the flow with the problem? I cannot get the behavior validation screen to come up when I try.

**Comment by phoenixy1** [comment]
Oh -- it would also be helpful if you could provide a `link_session_id` and/or your client ID so we can look up what happened here.

**Comment by ZnNozomi** [comment]
Thanks for your reply @phoenixy1 
I uploaded a video of me operating Plaid  https://drive.google.com/file/d/1u76lRdO0h27eojJ7hJiYe5xHt2CW-FLn/view
Let me just describe my problem：
The previous steps are all normal, but when I click back on the Google Verification page and do not authenticate, I will get this error

**Comment by phoenixy1** [comment]
@ZnNozomi thank you for the details!

Is this blocking you? 
We would expect users to authenticate instead of hitting "back".

**Comment by ZnNozomi** [comment]
The normal process is fine.
However, this problem occurs when the user wants to back out or exit, affecting the system flow.
Is there any way to listen for this error so I can act accordingly

**Comment by phoenixy1** [comment]
Do you get a link event associated with this issue? If so, that would be the link event to listen for. (For more details on listening for events, see https://plaid.com/docs/link/web/#onevent)

**Comment by ZnNozomi** [comment]
I'm sorry I had a few days off
No events or errors are returned in the 'onEvent' listener

**Comment by phoenixy1** [comment]
I've filed a bug with our Link team -- unfortunately I don't believe there is a way to listen for this event currently.
If there's anything else you need, let me know. If not I will close out this issue as the problem is not really with the Quickstart itself and the Link team does not follow this repo.

**Comment by ZnNozomi** [comment]
Thank you very much
No further questions
Where can I contact the Link team or track the progress of this issue?

**Comment by phoenixy1** [comment]
We don't have a public issue tracker for Link bugs unfortunately -- you can always contact Support / file a ticket via the Plaid Dashboard if you have questions or want to check in.
