### ISSUE TITLE
How this api 'https://sandbox.plaid.com/link/client/get' is getting called? 

### ISSUE THREAD

**Issue by shashinetsmartz** [plaid/quickstart#297]
So I'm following the quickstart repo with nodejs & reactjs. In quickstart repo once the create_link_token api successfully executed then the sandbox get api is being hit., In my code its not getting hit. I've passed the token as config in usePlaidLink() hook.

**Comment by phoenixy1** [comment]
/link/client/get is called after Link is initialized -- it is triggered by Plaid as part of the internal implementation details of Link and isn't something you should need to reason about.
