### ISSUE TITLE
Automated Micro Deposits Not Working

### ISSUE THREAD

**Issue by haydursek** [plaid/quickstart#302]
I am testing the automated micro deposits use case, and it seems to be not working. I am getting the following error when running the react frontend and node js backend.

Below is the information I am using to populate the UI, taken from the following link:

[](https://plaid.com/docs/auth/coverage/testing/#testing-automated-micro-deposits)

**Error Received:**

`vendors~LazyLink.js:2 POST https://sandbox.plaid.com/link/item/numbers/update 400 (Bad Request)`

**Comment by phoenixy1** [comment]
Hi, I think there might be some content missing from your ticket, as I don't see any of the information you are using to populate the UI.

Also just to check one common problem -- per the docs at https://plaid.com/docs/auth/coverage/automated/ "Not all Plaid Developer accounts are enabled for Automated Micro-deposits or Same Day Micro-deposits by default. To enable these features or check your status, contact your account manager or submit a product access Support ticket." -- have you already checked to confirm that you are enabled for this feature?

**Comment by phoenixy1** [comment]
Since I haven't heard anything further on this one and this isn't an issue related to the Plaid Quickstart, I'll close this issue. If you still need help on the issue, please file a ticket with Plaid support. thanks!

**Comment by haydursek** [comment]
@phoenixy1  
I am still having this issue. I was waiting for this to be enabled on the account, and this has been verified that it is, but when going through the flow with the required input data, I am receiving the following error now 

`{
  "display_message": null,
  "error_code": "INSTANT_MATCH_FAILED",
  "error_message": "Item cannot be verified through Instant Match. Ensure you are correctly enabling all auth features in Link.",
  "error_type": "ITEM_ERROR",
  "link_error_button": "",
  "link_error_heading": "",
  "link_error_icon": "",
  "link_error_message": "",
  "request_id": "Qtyi2RiqDnZbipn"
}`

I am not sure why this is attempting an instant match, when it should be doing the automated micro deposits flow based on the credentials.

Request Payload:
`{"link_token":"link-sandbox-2d8e1d29-651d-47a0-b7da-f0c2925efbb8","account_id":"5lqaxweRy8UVxEjL3ovxHBzyAvoNagFZLomy1","account_number":"1111222233330000","link_open_id":"a0018c20-7dc1-4fd6-8a79-387a476330b8","link_persistent_id":"b74f2c65-a227-4c92-94a2-283bda94cda1","link_session_id":"6692fce2-6399-4d96-ba51-27797952aaa4","public_token":"public-sandbox-998d5dcc-1c04-41c4-abbb-930ef8882d50","routing_number":"021000021","display_language":"en"}`

The input data I'm using is from the website 

[https://plaid.com/docs/auth/coverage/testing/#testing-automated-micro-deposits](url)

**Comment by phoenixy1** [comment]
Hmm -- I don't see anything obviously wrong in that request. Can you file a support ticket for this issue via the Plaid Dashboard at https://dashboard.plaid.com/support/new/product-and-development/product-troubleshooting/product-functionality? The Support team has access to additional diagnostic tools and permissions that enable them to view detailed information about your account and requests -- those of us answering here don't have access to that information and are limited in our ability to troubleshoot.

**Comment by btoo** [comment]
for me, the issue was that i needed to enable the specific functionality i was testing, e.g. for https://plaid.com/docs/auth/coverage/testing/#testing-same-day-micro-deposits i needed to include [`auth.same_day_microdeposits_enabled: true`](https://plaid.com/docs/api/link/#link-token-create-request-auth-same-day-microdeposits-enabled)
