### ISSUE TITLE
Automated Micro Deposits

### ISSUE THREAD

**Issue by haydursek** [plaid/quickstart#303]
I am having an issue on the Automated Micro Deposits. I have confirmed this is feature is enabled on the account, but when going through the flow with the required input data, I am receiving the following error now

`{ "display_message": null, "error_code": "INSTANT_MATCH_FAILED", "error_message": "Item cannot be verified through Instant Match. Ensure you are correctly enabling all auth features in Link.", "error_type": "ITEM_ERROR", "link_error_button": "", "link_error_heading": "", "link_error_icon": "", "link_error_message": "", "request_id": "Qtyi2RiqDnZbipn" }
`
I am not sure why this is attempting an instant match, when it should be doing the automated micro deposits flow based on the credentials.

**Request Payload:**
`{"link_token":"link-sandbox-2d8e1d29-651d-47a0-b7da-f0c2925efbb8","account_id":"5lqaxweRy8UVxEjL3ovxHBzyAvoNagFZLomy1","account_number":"1111222233330000","link_open_id":"a0018c20-7dc1-4fd6-8a79-387a476330b8","link_persistent_id":"b74f2c65-a227-4c92-94a2-283bda94cda1","link_session_id":"6692fce2-6399-4d96-ba51-27797952aaa4","public_token":"public-sandbox-998d5dcc-1c04-41c4-abbb-930ef8882d50","routing_number":"021000021","display_language":"en"}`

The input data I'm using is from the website

`https://plaid.com/docs/auth/coverage/testing/#testing-automated-micro-deposits`

**Comment by phoenixy1** [comment]
Hi, I answered this on the other ticket (https://github.com/plaid/quickstart/issues/302), so going to close out this one.
