### ISSUE TITLE
Can someone help me with processor/token/create..

### ISSUE THREAD

**Issue by bikudx742016** [plaid/quickstart#313]
I am trying to create processor token so that I can integrate with sila money.
Following the instructions from the plaid docs I am unable to get the processor token.
I am using Quickstar java to get access_token and account_id.
What's the other way to get processor token??

**Comment by phoenixy1** [comment]
Hi, there isn't enough information there to diagnose the problem. You can check out https://dashboard.plaid.com/activity/logs which will have more details about the error code you're hitting. If you're not able to debug the issue based on that information, you can file a support ticket at https://dashboard.plaid.com/support
