### ISSUE TITLE
Python backend with import json failure

### ISSUE THREAD

**Issue by blckassassin** [plaid/quickstart#323]
Issue:  While starting the server after installing the requirements list, an error occurs while importing packages and modules.  The following error is provided: `ImportError: cannot import name json from itsdangerous`

Expected: After running the start.sh bash file I would expect the server to successfully startup.

Possible solution: Adding `itsdangerous==2.0.1` to the requirements.txt file fixes the error.

**Comment by brianmacdonald** [comment]
Created #335 with fix

**Comment by blckassassin** [comment]
Closing since pull request is completed.
