### ISSUE TITLE
list of institutions not shown

### ISSUE THREAD

**Issue by cca32** [plaid/quickstart#33]
I'm having a similar problem where I run the server.py and it allows me to access the http://127.0.0.1:5000/ website with the following available:
![image](https://user-images.githubusercontent.com/40508291/41805550-c7ab6114-767a-11e8-97e5-d5d8315b6f81.png)

but then when i click open link, there is nothing available.
![image](https://user-images.githubusercontent.com/40508291/41805551-db5ebe0e-767a-11e8-960d-2a4cd4458985.png)

**Comment by michaelckelly** [comment]
@cca32 - Please go ahead and re-open this if you are still not able to get the Quickstart up-and-running!
