### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'data') at prettyPrintResponse

### ISSUE THREAD

**Issue by Karsenh** [plaid/quickstart#330]
I followed by the documentation on the plaid website as well as the YouTube guide which outlined the quick start docs with some minor changes such as including 'symlink=true' in the git clone command for Win users. Both of these failed in the same manner, throwing the following error:

`TypeError: Cannot read properties of undefined (reading 'data') at prettyPrintResponse` in my server console each time the React page loads / refreshes. Pretty sure this is on line 438 of the index.js iirc.

I noticed in the YouTube comment section other people having the same issue but I haven't seen any response.

Thank you.

**Comment by maxjowett** [comment]
Is there a fix for this?

**Comment by phoenixy1** [comment]
@maxjowett not yet! As mentioned above, this only occurs if the API call failed, and is a failure to display the backend error message gracefully on the frontend. You can still view the error code in the backend server logs or on dashboard.plaid.com. Let us know if you are stuck!

**Comment by jlehenbauer** [comment]
Got this error too, but haven't been able to fix it. Added a try/catch in the index.js to no avail. No records showing up in the Dashboard/server logs... any ideas?

For the record, I'm on Windows and *did* follow the steps (the second time.. woops) involving symlinks from Github.

**Comment by jlehenbauer** [comment]
> Got this error too, but haven't been able to fix it. Added a try/catch in the index.js to no avail. No records showing up in the Dashboard/server logs... any ideas?
> 
> For the record, I'm on Windows and _did_ follow the steps (the second time.. woops) involving symlinks from Github.

FIXED: had to do all of the following: 

1. Run `pip install -r requirements.txt` from within the `quickstart/python` folder
2. Start the server _from the python `start.sh` file_
3. Start the frontend as normally using `npm start` in the frontend folder
4. Done!

**Comment by Solutionsafoot** [comment]
how do you fix this for node js?

**Comment by phoenixy1** [comment]
@Solutionsafoot This issue as this is just a symptom of some kind of error happening during an API call and isn't specific enough to provide troubleshooting advice. To troubleshoot this issue, check the console or the Plaid API log at https://dashboard.plaid.com/activity/logs

**Comment by lordscarlet** [comment]
> @Solutionsafoot This issue as this is just a symptom of some kind of error happening during an API call and isn't specific enough to provide troubleshooting advice. To troubleshoot this issue, check the console or the Plaid API log at https://dashboard.plaid.com/activity/logs

as others have stated, this error is not accompanied by anything in the activity logs for me.

**Comment by lordscarlet** [comment]
interestingly, I added `console.log(error.response); on line `487` of `node/index.js`... and then I no longer received an error and was able to move along with attempting a link.

**Comment by JasonTheLucky** [comment]
I also got the error in Node, not able to see anything helpful in the console log and nothing in plaid logs. I tried the 487 and that did NOT do anything for me. Giving up on node and going to try Python next.

**Comment by saqib772** [comment]
Nothing is useful here, tried all things but Can't able to find the solutions. Plaid team pls update and fix this issuse as soon as possible pls.

**Comment by saqib772** [comment]
@phoenixy1 I tried but can't find any solution, in the plaid logs also nothing is seen. 
Check the following Pictures, pls help i want to make a ML Model on top of this.
![image](https://github.com/plaid/quickstart/assets/121972215/fb600814-5b59-486e-aae3-e4b699b2641d)

Froned:
![image](https://github.com/plaid/quickstart/assets/121972215/bbf5fbbb-30bb-4441-9420-02e84d14f08c)

Plaid Id:
![image](https://github.com/plaid/quickstart/assets/121972215/a82ff09b-a961-44ad-a369-f51794d174f9)

**Comment by andwilson36** [comment]
Moving the .env to the /node directory fixed the issue for me.

**Comment by jabok19** [comment]
> Copying the .env to the /node directory fixed the issue for me.

Same! Thank you!
