### ISSUE TITLE
Documentation: Typo in Quickstart 

### ISSUE THREAD

**Issue by elainabialkowski** [plaid/quickstart#355]
<img width="455" alt="image" src="https://user-images.githubusercontent.com/25761149/171499219-e59d2236-be81-4804-9093-0a809e7654d8.png">

_os.Getnev_ should be replaced with _os.Getenv_ in the first Golang sample under _How it works_

**Comment by phoenixy1** [comment]
nice catch. I just committed a fix to this that should be merged soon.
