### ISSUE TITLE
Unable to fetch link token

### ISSUE THREAD

**Issue by sierrataylor** [plaid/quickstart#357]
I have been getting the same problem discussed in an earlier issue. I have started from scratch multiple times, and tried running with and without Docker. I've made sure that my client id and secret key are included in the .env file, and while the site will run, it tells me that it can't get my link token. I'm using python if that helps.

**Comment by ghernandez-plaid** [comment]
Hi @sierrataylor, thanks for filing the issue. Could you perhaps post your code here and/or screenshot(s) of your setup / what you're encountering? Feel free to redact your client id and secret key values, too.

**Comment by sierrataylor** [comment]
@ghernandez-plaid 
![Screen Shot 2022-06-03 at 10 17 55 AM](https://user-images.githubusercontent.com/68617779/171872402-8d415bb5-4115-4248-b375-17ed2599a869.png)

**Comment by ghernandez-plaid** [comment]
Thanks for sharing @sierrataylor . Some screenshots of your terminal and/or dev console would help too. Also, you've probably already checked, but just want to confirm you are running the backend server? You have to start up the front end (client server) and back end for the Quickstart to run.

**Comment by sierrataylor** [comment]
![Screen Shot 2022-06-03 at 11 11 44 AM](https://user-images.githubusercontent.com/68617779/171882001-cd5e962e-45f8-4732-935e-baaee8eb6869.png)

I ran everything again and still got the same problem

**Comment by ghernandez-plaid** [comment]
> ![Screen Shot 2022-06-03 at 11 11 44 AM](https://user-images.githubusercontent.com/68617779/171882001-cd5e962e-45f8-4732-935e-baaee8eb6869.png)
> 
> I ran everything again and still got the same problem

Can you send me an email please? `ghernandez at plaid`

**Comment by sierrataylor** [comment]
Ok

**Comment by johnvullo96** [comment]
Were you able to solve this? I have been having the same issue for months

**Comment by sierrataylor** [comment]
No I was not.

**Comment by phoenixy1** [comment]
@sierrataylor @johnvullo96 sorry you're having issues, please feel free to file a support request via the Plaid developer dash if you need additional help!

**Comment by soapYE** [comment]
@sierrataylor @johnvullo96 Hi I met the same problems and I solved it by doing the git clone commands under administrator's permision. I am using windows.

**Comment by JoeyFenny** [comment]
I was able to fix it by using `make start` and `make stop` commands instead of `docker-compose up`

**Comment by wengxu** [comment]
yes . make up and make stop works.. issue is with the docker UI restart button

**Comment by smarath3** [comment]
Running on non-docker/local environment. For me, the fix was about setting my local server URI in 'Allowed redirect URIs' configuration in https://dashboard.plaid.com/developers/api
