### ISSUE TITLE
Saving data as json

### ISSUE THREAD

**Issue by sierrataylor** [plaid/quickstart#358]
I need to save some of this data to a json file. What is the best way to do that here?

**Comment by tnightengale** [comment]
You should edit the backend file in the language of your choice to serialize the json from a response into a file. This is not really the place to ask basic questions about programming.

**Comment by sierrataylor** [comment]
I'm only asking because I can't even get the quickstart to run let alone serialize anything

**Comment by tnightengale** [comment]
@sierrataylor Very fair, I just opened #362 to demonstrate how the quickstart fails end-to-end for development mode with docker compose. Please chime in there as well if you've encountered the same issues.
