### ISSUE TITLE
Why is `selectAccount` feature not documented? What else is not documented?

### ISSUE THREAD

**Issue by ktiedt** [plaid/quickstart#36]
Luckily for us, a co-worker had an old demo app that listed this feature... but now we are wondering, what else is missing from the doc?

For reference, the only mention of the selectAccount feature appears to be this comment...
```
      // The metadata object contains info about the institution the
      // user selected and the account ID or IDs, if the
      // Select Account view is enabled.
```

https://plaid.com/docs/#parameter-reference

**Comment by michaelckelly** [comment]
@ktiedt - That looks like a typo in our docs (specifically the third line in that comment), we'll get it sorted out.

You can customize Link -- including enabling the [Select Account pane][2] -- straight from your [Dashboard][1]. We moved this to the Dashboard to make it easier to surface more complex customizations such as multi-account select for the Select Account pane.

[1]: https://dashboard.plaid.com/link
[2]: https://dashboard.plaid.com/link/account-select

**Comment by ktiedt** [comment]
@michaelckelly ok, but until we go beyond sandbox interactions, we do not have access to dashboard do we? Because the other feature my product team is asking about, is "can we allow multiple accounts to be selected too?"

**Comment by ktiedt** [comment]
@michaelckelly thanks! Yeah I am trying to track down who did that, so we don't end up with disparate keys floating around.

Also, kudos on the amazingly fast response. Hopefully all the features do make it back into the documentation pages too though, that would be helpful for teams researching capabilities before committing to a product ;)

**Comment by michaelckelly** [comment]
> @michaelckelly thanks! Yeah I am trying to track down who did that, so we don't end up with disparate keys floating around.

👍 

> Also, kudos on the amazingly fast response. Hopefully all the features do make it back into the documentation pages too though, that would be helpful for teams researching capabilities before committing to a product ;)

That feedback is noted -- thanks for sharing it. I'll pass it along to the rest of the team too.

Happy building!

**Comment by tzsk-rw** [comment]
@michaelckelly I think having an Override of the `selectAccount` from API would be really good. Whatever is set in the dashboard can be the default. But in some cases I want to select a particular account but in other cases I just want to authorize an institution. In my use case I'm required to do both.

Which is forcing me to have 2 different plaid account with `selectAccount` **DISABLED** and the other one with **ENABLED** which is really painful. I would love to see an override.

Can we have that please?

**Comment by rrigoni** [comment]
If I disable the accounts selection view in the dashboard the `selectAccount` parameter works in the Link initialization. If I keep it enabled in the dashboard it ignores the `selectAccount`. 

That is inconsistent.

**Comment by stevanpopo** [comment]
@michaelckelly does the select account feature work in Sandbox mode? I have got this enabled in my dashboard but when I am selecting only specific accounts I still seem to get all data.
