### ISSUE TITLE
Plaid Quickstart Doesn't Support My Institution

### ISSUE THREAD

**Issue by cmay10** [plaid/quickstart#369]
I'm trying to get an access token for my bank account so I can create my own personal budget. I went through the quickstart and when I click on my institution it says "Connectivity not supported". However I have connected to my bank account through Plaid using other apps before. Is there another way to get an access token?

**Comment by phoenixy1** [comment]
The issue is with how you've configured the .eng file, probably by listing too many products -- see https://plaid.com/docs/link/troubleshooting/#missing-institutions-or-connectivity-not-supported-error
