### ISSUE TITLE
Conflicting peer dependency while trying `make up language=python`

### ISSUE THREAD

**Issue by sardine8042** [plaid/quickstart#388]
Hello, I'm following the instructions for the quickstart. After trying `make up language=python`, I hit this snag:

```
#0 2.448 npm ERR! Conflicting peer dependency: typescript@3.9.10
#0 2.448 npm ERR! node_modules/typescript
#0 2.448 npm ERR!   peerOptional typescript@"^3.2.1" from react-scripts@4.0.1
#0 2.448 npm ERR!   node_modules/react-scripts
#0 2.448 npm ERR!     react-scripts@"4.0.1" from the root project
```

If it matters, I'm running this on an M1 Mac.

Steps to reproduce:
- Clone the quickstart
- run `make up language=python`

I've tried adding `--legacy-peer-deps` to line 13 of the frontend Dockerfile, but that runs into more issues. Adding `--force` seems to bypass the error, but I'm a bit concerned there may cause problems down the line. Is anyone else running into this issue?

**Comment by phoenixy1** [comment]
Hmm, I wasn't able to reproduce that. Do you get the same issue when using the non-Docker version?

`--force` shouldn't case any problems down the line.

cc: @lindawoo-plaid

**Comment by horatiothomas** [comment]
Can confirm this happens to me when I use docker, but works with the non-Docker version. I'm also on an M1 Mac fwiw.

**Comment by phoenixy1** [comment]
This is now fixed! In case you're curious, the factor was the version of npm installed, rather than the Mac chip. Thank you for reporting this issue!
