### ISSUE TITLE
"You may need to update your app in order to connect..." Error

### ISSUE THREAD

**Issue by Epod** [plaid/quickstart#394]
When trying to link an account, "Chase" as an example, you instantly get taken to the following message:

![Screen Shot 2022-12-04 at 9 21 50 PM](https://user-images.githubusercontent.com/49006/205535454-bc3bf62d-1b8e-4777-9152-d46fcf36b633.png)

No option to even enter credentials. That just instantly comes up with using the latest version of this quick start app.

**Comment by phoenixy1** [comment]
@Epod This happens if you are running in a non-Sandbox environment and not enabled for OAuth. For more details, see https://plaid.com/docs/link/troubleshooting/#you-may-need-to-update-your-app-or-something-went-wrong-error-message and lmk if that doesn't solve your problem.
