### ISSUE TITLE
Unable to fetch link_token: Error

### ISSUE THREAD

**Issue by vkb008** [plaid/quickstart#405]
Hello All:

I am attempting the quickstart project with Docker on a Mac OS and I am getting this error when I attempt to run the app:

<img width="1147" alt="Quickstart Status" src="https://user-images.githubusercontent.com/4166458/209707994-3d35b49e-dc6d-48ed-be41-fbe1bf987f34.png">

Outputted logs in Terminal:

<img width="1582" alt="Screenshot 2022-12-25 at 5 11 58 PM" src="https://user-images.githubusercontent.com/4166458/209707982-2dbb31e8-43b8-410e-8c52-05d1c2270126.png">

<img width="1582" alt="Screenshot 2022-12-25 at 5 12 45 PM" src="https://user-images.githubusercontent.com/4166458/209708222-fb3d23e7-fa27-468f-b7b1-d26e753a8fb5.png">

Screenshot of .env file I attempted to use:

<img width="794" alt="env file screenshot" src="https://user-images.githubusercontent.com/4166458/209708239-5fa18bfc-ef5b-42e2-9079-6b80e8e4932b.png">
  
I have reached out to plaid support and a support worker's feedback was that he was getting the same issue I was getting and was going to reach out to the team for more help. But I thought in parallel I would also reach out here and see if there was any additional support here as well. Thanks in advance!!

**Comment by vkb008** [comment]
https://plaid.com/docs/quickstart/ - link to quickstart instructions I used.

**Comment by phoenixy1** [comment]
@vkb008 thanks for reporting this! I'll take a look. In the meantime, this appears to impact only the Docker-based version of the instructions, so as a workaround you should be able to use the non-Docker instructions.

**Comment by phoenixy1** [comment]
@vkb008 I believe I fixed the issue, there was a copy and paste error that caused issues with Docker. It may be a day or two before I get a code review stamp, but you should be able to manually apply the fix in the linked PR (change frontend/src/setupProxy.js line 7 to `target: process.env.REACT_APP_API_HOST || 'http://localhost:8000',`) and I believe that should resolve the issue.

**Comment by vkb008** [comment]
@phoenixy1 Thank you for the code fix! It looks like that solved the error and I can continue moving forward with the Docker quickstart tutorial 😄
