### ISSUE TITLE
Query EU ISIN?

### ISSUE THREAD

**Issue by pataquets** [plaid/quickstart#409]
Hi.
I'm browsing plaid API for a personal need.
As per your [docs](https://plaid.com/docs/investments/), only US/Canada ISINs are available.
Are EU ones queryable by another means? Any plans to support it in the future?
Thanks!

**Comment by phoenixy1** [comment]
Hi, unfortunately Plaid does not offer this capability in Europe and we don't currently have any plans to add it.
