### ISSUE TITLE
Missing products causes quickstart failure

### ISSUE THREAD

**Issue by justinxreese** [plaid/quickstart#42]
If following the Ruby instructions at https://dashboard.plaid.com/overview/sandbox, the institution search will fail to populate with any banks. Inspecting the javascript console will warn you that a valid list of products must be set.

The documentation neglects to mention the `ENV['PLAID_PRODUCTS']` variable that is used on line 195 of `views/index.erb` and causes this error if it is not set. Once this is set, the institution search works fine. Since the purpose of this repo is to quickly build a templated Plaid application, this should be either hard-coded into index.erb or mentioned in the documentation near "Running the walkthrough application".

I used `["auth", "transactions", "income", "identity", "assets"]`, which is all of the products it accepts as valid.

**Comment by michaelckelly** [comment]
@justinxreese Thanks for flagging this and sorry for the confusion this caused - we'll get this fixed right away.

**Comment by justinxreese** [comment]
@michaelckelly fantastic. Great, thorough docs and simple implementation otherwise. Very happy with how easy it was to get going.
