### ISSUE TITLE
Error when starting front end with Node version 18 

### ISSUE THREAD

**Issue by MAsimSENG** [plaid/quickstart#428]
Following the quick start guide: 

cd quickstart/frontend
npm install
npm start

**If we have node version 18.0 we get an error `Invalid options object. Dev Server has been initialized using an options object that does not match the API schema`.**

**Comment by MAsimSENG** [comment]
<img width="849" alt="image" src="https://github.com/plaid/quickstart/assets/42298613/8825d987-ae0b-43e9-a0c9-c1b00834610c">

**Comment by phoenixy1** [comment]
Thanks for the report! I have a fix in flight that's waiting for code review, but in the meantime a few workarounds are: 

1) export `DANGEROUSLY_DISABLE_HOST_CHECK=true`
2) Delete  the line "proxy": "http://127.0.0.1:8000" from the package.json file 
3) Use node 16

Any of those should resolve the issue

**Comment by MAsimSENG** [comment]
Thanks @phoenixy1  I used node 17 and It worked
