### ISSUE TITLE
Unable to fetch link_token:

### ISSUE THREAD

**Issue by Axiom0599** [plaid/quickstart#435]
I followed the documentation properly. And even though, I get this error.![Screenshot 2023-07-16 at 8 33 34 AM](https://github.com/plaid/quickstart/assets/63239974/3d4dc6bd-c69f-4cdc-bb95-31b9db3cfd94)

**Comment by phoenixy1** [comment]
I was not able to reproduce this issue based on the information provided, so I can't determine that there's anything wrong with the Quickstart. If you need more help, please file a support ticket via the Dashboard, and include detailed information including the exact steps you took, the troubleshooting steps you have followed (there's a troubleshooting guide in the Quickstart readme), and the request_id for your request to /link/token/create, which can be found in the Logs section of the Dashboard.
