### ISSUE TITLE
NPM audit reveals dependency vulnerabilities

### ISSUE THREAD

**Issue by StephenKoller** [plaid/quickstart#44]
Pulled the quickstart repo to test out the Node walkthrough app.

After running `npm install`, I'm seeing some vulnerabilities in the `express` package highlighted by npm's audit tool.

![image](https://user-images.githubusercontent.com/1561673/49820466-f2a0df00-fd45-11e8-8866-4e332f77c8c9.png)

**Comment by michaelckelly** [comment]
Thanks @StephenKoller - we'll work to get the dependencies updated right away.
