### ISSUE TITLE
python quickstart url not found

### ISSUE THREAD

**Issue by kvnsng** [plaid/quickstart#452]
I'm using python 3.9 and installed the dependencies in `requirements.txt` in the python directory. After I run `python3 server.py`, my terminal says the app is running on http://127.0.0.1:8000 but when I go there I'm getting url not found error... 

Any suggestions?

**Comment by phoenixy1** [comment]
Check out the instructions in the README, which address this issue: https://github.com/plaid/quickstart/blob/master/README.md#1-running-the-backend

**Comment by kvnsng** [comment]
ah oops. didn't realize there was a separate frontend!
