### ISSUE TITLE
Quickstart Python Server Returns 404 

### ISSUE THREAD

**Issue by ryan-c-hsu** [plaid/quickstart#453]
Hello,

After running `python3 server.py`, I am receiving the following errors.

```
"GET / HTTP/1.1" 404 -
"GET /favicon.ico HTTP/1.1" 404 -
```

Would anybody know where this is coming from? 

Thanks.

**Comment by ryan-c-hsu** [comment]
I also got this when running node for the backend server

```
plaid-quickstart server listening on port 8000
TypeError: Cannot read properties of undefined (reading 'data')
```

This seems like a symlinks issue but I have turned it on when cloning the repo

**Comment by ryan-c-hsu** [comment]
Nevermind. I didn't run symlink flag with administrator access so it failed. 

I was able to get the node server running but I would prefer using python. Is there a way to address the python issue?

**Comment by phoenixy1** [comment]
The issue you describe above can occur if you try to go to the server directly on port 8000 rather than running the frontend and accessing the frontend server as described in the instructions. Other than by doing that, I wasn't able to repro the issue, so don't have any other suggestions.
