### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by CAT1210** [plaid/quickstart#457]
I am getting this error when I click on my bank and click to login. It appears I am getting it for all banks that perhaps have OAUTH (Chase, BoA, etc) as well. My .env seems correct and I have had quickstart working before and haven't changed anything; id, secret, development all populated and redirect is blank. I rotated the secret to see if that would make a difference but it didn't. I have tried with node and Python and results are the same. Can anybody give me a hand on why I am seeing this message box now? Thanks!

**Comment by phoenixy1** [comment]
some troubleshooting suggestions:
1. make sure you are using sandbox environment -- if you are using development, you need to complete the [oauth requirements](https://plaid.com/docs/link/oauth/#prerequisites-for-adding-oauth-support).
2. check the console log, terminal, and [plaid dashboard logs](https://dashboard.plaid.com/developers/logs) for any errors

**Comment by CAT1210** [comment]
Okay, looks like one of those requirements is Production access, which I haven't really thought about. So, if I use sandbox, I can only use Platypus? I ask because when I select my institution in Sandbox, click to login, and it takes me to Platypus login screen (does this with any OAUTH bank that I select)...

**Comment by phoenixy1** [comment]
> Okay, looks like one of those requirements is Production access, which I haven't really thought about. So, if I use sandbox, I can only use Platypus? I ask because when I select my institution in Sandbox, click to login, and it takes me to Platypus login screen (does this with any OAUTH bank that I select)...

Sandbox does support multiple banks, but it uses the Platypus OAuth flow for all OAuth banks. To test with the real, bank-specific OAuth flows, you'd have to apply for and receive production access, then test in development.

**Comment by gbdavidx** [comment]
Can i use sandbox mode and still link my bank for my own live data?

**Comment by phoenixy1** [comment]
no. Sandbox mode only uses fake (Sandbox) data.
