### ISSUE TITLE
Getting Error when trying to execute the command npm install in frontend folder

### ISSUE THREAD

**Issue by VAmsIdhAR2340** [plaid/quickstart#458]
Hi all,
I am getting an error when I am trying to install npm install in the frontend folder. Below is the error message:

PS E:\quickstart\frontend> npx npm-force-resolutions
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path C:\Users\vamsi\AppData\Roaming\npm
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, lstat 'C:\Users\vamsi\AppData\Roaming\npm'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

Can any one help with my issue.
![Screenshot (29)](https://github.com/plaid/quickstart/assets/79391273/56e979fd-b1bb-43d7-bbe1-9317ca83cb07)

**Comment by mondiriariana** [comment]
have you tried npm install --force ?

**Comment by phoenixy1** [comment]
closing this issue as it does not appear to be related to the quickstart itself
