### ISSUE TITLE
use Plaid services with desktop local application directly 

### ISSUE THREAD

**Issue by darkomenx** [plaid/quickstart#472]
Hello Plaid,

Is there a solution to communicate with your banking solutions from a client software installed locally on the user’s OS?

Avoiding going through a third-party backend server, but allowing a desktop application to use your services?

Thank you for your advice and feedback

**Comment by darkomenx** [comment]
Ok so if I restrict/hide/crypt API keys and tokens it's become possible.

**Comment by phoenixy1** [comment]
No. It is not supported. You cannot do this without distributing your API key to client devices, which is a violation of Plaid's security policy.
