### ISSUE TITLE
Trying to fetch institution by id throws cors error in production

### ISSUE THREAD

**Issue by sumanla13a** [plaid/quickstart#48]
Hi,

I am sending a post request to `/institutions/get_by_id` from browser,
Until now I was in sandbox environment where it was working fine,

But after deploying it to production, it throws me cors error
```
has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
```

Can this not work in production?
Should I send this request from my server instead of my client?

**Comment by davidzhanghp** [comment]
Hi @sumanla13a,

Those requests should be made server-side. CORS requests are only supported for Plaid link requests.
