### ISSUE TITLE
Randomly Started Getting Access Denied Error

### ISSUE THREAD

**Issue by SaiMupparaju** [plaid/quickstart#494]
So, I've been working on an app using Plaid for weeks now, I was able to get the API up and running for my app but up till now I've still been in Sandbox mode. All of a sudden I try working through the whole Plaid flow like normal yesterday and now no matter what when a user tries to add an item they choose a bank account -> go to enter credentials -> the credentials page closes after a few seconds automatically. I was very confused so I  opened the Plaid Quickstart and even there I've been running into the same issue. Here's an example of the error log from the quickstart.

Link-session-id: b66398f0-048e-4fa6-8da3-1f09c89e0f92
Error Code: Insufficient Credentials
Token: link-sandbox-442be84f-4e84-4583-88a9-3ebf1f2413fb

I'm really not sure why this is happening, I cloned my project onto a different device and it worked fine there. Have I been IP banned? If so, I'm really not sure what I have done. But I imagine that if Plaid wanted to they would have banned my account instead of IP. My laptop has been running a bit slower, could it be some Malware interfering with my network?

**Comment by SaiMupparaju** [comment]
Just for some more info, I using Node and the console in the quickstart prints this error: vendors~flink.js:2 Error: Error fetching https://sandbox.plaid.com/link/workflow/poll
    at _callee3$ (flink.js:1:102991)
    at tryCatch (vendors~flink.js:2:520052)
    at Generator.<anonymous> (vendors~flink.js:2:521816)
    at Generator.throw (vendors~flink.js:2:520614)
    at asyncGeneratorStep (vendors~flink.js:2:75262)
    at _throw (vendors~flink.js:2:75590)

**Comment by SaiMupparaju** [comment]
> It's possible that your IP address was automatically flagged for excessive failed login attempts or other behavior that triggered Plaid's risk flows. If so, try waiting a few days and eventually your device should work again. If that doesn't resolve the problem, free to open a Support ticket if you still need help.

Hey, it's been a few days and I tried it and QuickStart worked again so it does indeed seem like an IP issue. Just for future reference, what should I do to prevent this? IIRC I wasn't doing anything out of the ordinary. I found an issue in a previous part of my code (now fixed) where accounts/get was being called more than needed. Would this potentially have something to do with it?

**Comment by phoenixy1** [comment]
For security reasons, we don't disclose details of our risk flagging algorithms, but some examples of reasons for device flagging could include repeated login attempts from an untrustworthy network (for example, using a public network that a bad actor had also used) or a large volume of failed login attempts in a short amount of time.
