### ISSUE TITLE
[Limited production] - Internal error occured

### ISSUE THREAD

**Issue by jdartigalongue** [plaid/quickstart#501]
I have been trying the quickstart guide and it works perfectly fine when using the Sanbox environment. 

However, I am getting a "Something went wrong / Internal error" when trying to use the production environment (Limited production access for now). It displays the error right away so I don't even get to see the institution selection screen. 

I can see the error in the console developer logs but with no relevant details. Could you please provide guidance on how to troubleshoot this error?

Link Session ID [ea06d069-8782-4659-93b9-5fe3b9a28d5f]

**Comment by phoenixy1** [comment]
To avoid this error, you need to set a use case for Link, which you can do here: https://dashboard.plaid.com/link/data-transparency-v5 
The requirement to provide a use case is new and we're working on clearer error messaging but it hasn't quite shipped yet.
