### ISSUE TITLE
How to do money transfer?

### ISSUE THREAD

**Issue by thomsonimjd** [plaid/quickstart#51]
I use nodejs quick start project, where I could logoin to any of the financial institutions and then could get few apis to accesss. I would like to transfer few usd to another account, how do I do that?

**Comment by michaelckelly** [comment]
Hey @thomsonimjd - in order to move money, you'll need to use Plaid in conjunction with a payment processor. Check out https://fin.plaid.com/articles/inside-ach-payments-with-stripe-and-plaid for more of an in depth overview!

**Comment by thomsonimjd** [comment]
@michaelckelly thanks buddy, let me work on it and get back to you
