### ISSUE TITLE
Ruby quickstart bad request

### ISSUE THREAD

**Issue by georgetmayorga** [plaid/quickstart#61]
When doing the default ruby quickstart walk through, the app breaks with the following ouput

```
POST https://sandbox.plaid.com/link/client/get 400 (Bad Request)
Error: Error retrieving info for public key. Make sure that the entered key is correct. Find your public key in your Dashboard (https://dashboard.plaid.com/account/keys).
```

The public keys are right—any ideas as to why that POST endpoint would be a bad request?

**Comment by georgetmayorga** [comment]
Figured it out and added a PR to solve the issue! https://github.com/plaid/quickstart/pull/62

**Comment by michaelckelly** [comment]
Thanks for that PR @georgetmayorga!
