### ISSUE TITLE
Plaid Queries

### ISSUE THREAD

**Issue by DomhnallBoyle** [plaid/quickstart#70]
Hi @michaelckelly,

Does plaid allow you to limit the location for institutions to select from e.g. UK? 

Also, can plaid limit these UK institutions that use Open Banking only to select from or how can this be done? 

Thanks

**Comment by vaMuchenje** [comment]
@DomhnallBoyle 

Yes you can. When you set your secrets for API keys (also known as environment variables) just set a variable called  PLAID_COUNTRY_CODES equal to one or more of the options US,CA,IE,GB,FR,ES

For example:
1) US only is PLAID_COUNTRY_CODES= US
2) US, Canada and Spain would be PLAID_COUNTRY_CODES=US,CA,ES

Then when you create your client object in your main file or server.py file, you can either fetch the environment value or set in place there. Like this code here:

`PLAID_COUNTRY_CODES = os.getenv('PLAID_COUNTRY_CODES', 'US,CA,GB,FR,ES')`

and add it to your Link template along with your other variables like this:
`
@app.route('/')
def index():
  return render_template(
    'index.ejs',
    plaid_public_key=PLAID_PUBLIC_KEY,
    plaid_environment=PLAID_ENV,
    plaid_products=PLAID_PRODUCTS,
    plaid_country_codes=PLAID_COUNTRY_CODES,
  )
`

**Comment by skylarmb** [comment]
Hi there @DomhnallBoyle if you still need help with this could you file a support ticket? Thanks!

https://dashboard.plaid.com/support/new/product-and-development
