### ISSUE TITLE
invalid public_key provided

### ISSUE THREAD

**Issue by Thilakeswar** [plaid/quickstart#72]
Getting error when trying to load Plaid JS.
Error: "invalid public_key provided. Request ID: sFgOMO4W1g8UBY1"
    initialize https://cdn.plaid.com/link/2.0.289/LazyLink.js:1
    e https://cdn.plaid.com/link/2.0.289/link-dynamic-loader.js:1
    T https://cdn.plaid.com/link/2.0.289/link-dynamic-loader.js:1
    t https://cdn.plaid.com/link/2.0.289/link-dynamic-loader.js:8

Please check and let me know what is the issue here. I have attached the Request ID for Reference.

**Comment by blackmarkt** [comment]
Same here and also have the issue of nothing happening when the "Connect with Plaid" button is pushed. I modified the code to hard code the environment variables but now get the above the message _**invalid public_key provided. Request ID**_

**Comment by skylarmb** [comment]
This is an environment variable issue. When you ran the following command did you fill out your CLIENT_ID, SECRET, and PUBLIC_KEY correctly?

```
PLAID_CLIENT_ID='CLIENT_ID' \
PLAID_SECRET='SECRET' \
PLAID_PUBLIC_KEY='PUBLIC_KEY' \
PLAID_ENV='sandbox' \
PLAID_PRODUCTS='transactions' \
node index.js
```

**Comment by szhongren** [comment]
@Thilakeswar @blackmarkt can you try using my branch from this PR? https://github.com/plaid/quickstart/pull/113 looks like the error I saw.

**Comment by skylarmb** [comment]
@Thilakeswar I am going to close this. This simply has to do with how you are supplying the env vars at the command line. @szhongren if you have details on exactly what you did that fixed it, i would appreciate you posting them here.
