### ISSUE TITLE
golang quickstart app appears to have some copypasta

### ISSUE THREAD

**Issue by xanderflood** [plaid/quickstart#73]
The ruby Quickstart app has two endpoints `/get_acess_token` (which takes a form field `public_token`) and `/set_access_token` (which takes a form field `access_token`). It calls them each under different circumstances in the template view.

The golang has only an endpoint `/set_acess_token`, which is defined in a function called `getAccessToken`, and which only references the `public_token` form field, not the `access_token` one. However, the golang template view calls `set_access_token` with an `access_token` field, which will always be ignored and the request will always fail because the `public_token` field is empty. It seems like this logic may have been copied over from the ruby one, changed a bit, and not properly resolved? I'd be happy to sort through it and submit a fix, but I just want to make sure that this is actually a mistake and not something I'm just misunderstanding.

The relevant code from the golang server is [here](https://github.com/plaid/quickstart/blob/master/go/server.go#L37), and it's added to the Gin router [here](https://github.com/plaid/quickstart/blob/master/go/server.go#L180). The JS logic that appears to be misusing this endpoint is [here](https://github.com/plaid/quickstart/blob/master/go/templates/index.tmpl#L224).

**Comment by fir1** [comment]
Any updates on this issue? Could you suggest the fix please? Thanks.

**Comment by davidzhanghp** [comment]
@xanderflood I believe this is no longer relevant. Sorry for the late response
