### ISSUE TITLE
The button in the Quickstart sample app does nothing

### ISSUE THREAD

**Issue by vaMuchenje** [plaid/quickstart#76]
Is it not supposed to pop-up a selection interface where i can choose a bank? When i click on it, nothing happens. I have tried it on 3 different machines now.

**Comment by tavy88** [comment]
Yeah, it's broken...

**Comment by MattHuntebrinker** [comment]
Any update on this?

**Comment by tavy88** [comment]
It works. Make sure you have all the keys required in their JS script. I found out that mine wasn't picked up properly. Try hardcoding the values to make it work and then figure a way to pass them as ENV.

**Comment by jbuenemann** [comment]
@tavy88 is right. In Python I needed to export the environment variables first. Then it runs fine.

**Comment by blackmarkt** [comment]
thanks @jbuenemann and @tavy88 this worked for me.
```
export PLAID_CLIENT_ID='somechars1234'
export PLAID_PUBLIC_KEY='somemorechars1234'
export PLAID_SECRET='somesecretchars1234'
export PLAID_ENV='sandbox'
```

**Comment by skylarmb** [comment]
@vaMuchenje were you able to get this working by populating the environment variables as mentioned by others in this thread?

**Comment by aditya08** [comment]
Removing the single quotes around PLAID_CLIENT_ID, PLAID_PUBLIC_KEY and PLAID_SECRET solved the issue with python environment variables on Windows. 

Also double check that you are using the correct PLAID_SECRET. There is one for development and another for sandbox.

**Comment by phoenixy1** [comment]
moved to closed but still open for some reason -- closing for real this time
