### ISSUE TITLE
Ruby quickstart app: unable to get Identity

### ISSUE THREAD

**Issue by carmelag** [plaid/quickstart#78]
After running the ruby example app. I tried to call _get Identity_, but I got the following error:

*Uncaught TypeError: Cannot read property 'names' of undefined*

![Screen Shot 2019-12-04 at 4 47 32 PM](https://user-images.githubusercontent.com/5394906/70158193-2099d480-16b7-11ea-84a0-a76abee75ec8.png)

It happens with multiple banks (I tried 3-4 banks).
Nothing is shown under the section to send a request to get Identity. Nor a result neither an error.

**Comment by phoenixy1** [comment]
I think some changes I made a few months ago fixed this one.  Please re-open if it's still a problem.
