### ISSUE TITLE
node env variable  'No environment variable named "PLAID_CLIENT_ID"'

### ISSUE THREAD

**Issue by mo-miisol-ltd** [plaid/quickstart#99]
Been a pain getting this initial walk through app working using node . 

[Error [UnsetVariableError]: No environment variable named "PLAID_CLIENT_ID"] {
  message: 'No environment variable named "PLAID_CLIENT_ID"'

Solution:
Will be good to include dotenv module to externalise the properties , So they can be read from .env file. 
https://www.npmjs.com/package/dotenv

add following line in  file index.js 

require('dotenv').config();

create .env file in node root dir with following lines: 
APP_PORT=8000
PLAID_CLIENT_ID=<replace with your clientid>
PLAID_SECRET=xx
PLAID_PUBLIC_KEY=xx
PLAID_PRODUCTS=transactions
PLAID_COUNTRY_CODES=US,CA,GB,FR,ES,IE
PLAID_ENV=sandbox

**Comment by AriGibson** [comment]
Agreed. This setup was definitely a pain. My PR should be an easy fix 😄 ; I'm glad I'm not the only one who was struggling here!

**Comment by shuyttr** [comment]
@mo-miisol-ltd This solution is great!
> I just wanted to flesh out the code below for people struggling to use the `.env` variables in their Node code.

`.env` file looks like:
```.env
APP_PORT=8000
PLAID_CLIENT_ID=your_id
PLAID_SECRET=your_development_secret
PLAID_PUBLIC_KEY=your_publickey
PLAID_PRODUCTS=transactions
PLAID_COUNTRY_CODES=US
PLAID_ENV=sandbox
```
`index.js` file looks like:
```javascript
var APP_PORT = envvar.number('APP_PORT', 8000);
var PLAID_CLIENT_ID = process.env.PLAID_CLIENT_ID;
var PLAID_SECRET = process.env.PLAID_SECRET;
var PLAID_PUBLIC_KEY = process.env.PLAID_PUBLIC_KEY;
var PLAID_ENV = envvar.string('PLAID_ENV', 'sandbox');
```
> For the `APP_PORT` and `PLAID_ENV` assignments in the `index.js`, you can leave it unedited, provided you want to run the server on port 8000.

**Comment by phoenixy1** [comment]
@AriGibson's PR has since been incorporated into master, so this should be resolved.  Thank you @AriGibson !
